#!/usr/bin/env ruby
# frozen_string_literal: true

require 'xcodeproj'

project_path = File.expand_path('../../ios/Runner.xcodeproj', __dir__)
project = Xcodeproj::Project.open(project_path)

runner_target = project.targets.find { |t| t.name == 'Runner' }
raise 'Runner target not found' unless runner_target

runner_bundle_id =
  runner_target.build_configurations.find { |c| c.name == 'Release' }&.build_settings&.[]('PRODUCT_BUNDLE_IDENTIFIER') ||
  runner_target.build_configurations.first&.build_settings&.[]('PRODUCT_BUNDLE_IDENTIFIER') ||
  'com.follow.flClash'
packet_tunnel_bundle_id = "#{runner_bundle_id}.PacketTunnel"

runner_group = project.main_group.find_subpath('Runner', true)
packet_group = project.main_group.find_subpath('PacketTunnel', true)
products_group = project.products_group

# Ensure file references exist
service_plugin_ref = runner_group.files.find { |f| f.path == 'ServicePlugin.swift' } ||
  runner_group.new_file('ServicePlugin.swift')
runner_entitlements_ref = runner_group.files.find { |f| f.path == 'Runner.entitlements' } ||
  runner_group.new_file('Runner.entitlements')

provider_ref = packet_group.files.find { |f| f.path == 'PacketTunnelProvider.swift' } ||
  packet_group.new_file('PacketTunnelProvider.swift')
packet_info_ref = packet_group.files.find { |f| f.path == 'Info.plist' } ||
  packet_group.new_file('Info.plist')
packet_entitlements_ref = packet_group.files.find { |f| f.path == 'PacketTunnel.entitlements' } ||
  packet_group.new_file('PacketTunnel.entitlements')

# Ensure NetworkExtension framework reference exists
frameworks_group = project.frameworks_group || project.main_group.new_group('Frameworks')
network_ext_ref = frameworks_group.files.find { |f| f.path == 'System/Library/Frameworks/NetworkExtension.framework' } ||
  frameworks_group.new_file('System/Library/Frameworks/NetworkExtension.framework')

# Remove non-portable Foundation SDK references auto-generated by xcodeproj on non-macOS hosts.
project.files
       .select { |f| f.display_name == 'Foundation.framework' && f.path.to_s.include?('/SDKs/iPhoneOS') }
       .each(&:remove_from_project)

# Runner: add ServicePlugin.swift to sources
unless runner_target.source_build_phase.files_references.include?(service_plugin_ref)
  runner_target.source_build_phase.add_file_reference(service_plugin_ref)
end

# Runner: link NetworkExtension framework
unless runner_target.frameworks_build_phase.files_references.include?(network_ext_ref)
  runner_target.frameworks_build_phase.add_file_reference(network_ext_ref)
end

# Configure Runner entitlements for all build configs
runner_target.build_configurations.each do |config|
  config.build_settings['CODE_SIGN_ENTITLEMENTS'] = 'Runner/Runner.entitlements'
end

# Create extension target if missing
packet_target = project.targets.find { |t| t.name == 'OrangePacketTunnel' }
unless packet_target
  packet_target = project.new_target(:app_extension, 'OrangePacketTunnel', :ios, '13.0')
  packet_target.product_reference.name = 'OrangePacketTunnel.appex'
  products_group << packet_target.product_reference unless products_group.children.include?(packet_target.product_reference)

  # Embed app extension in Runner
  embed_phase = runner_target.copy_files_build_phases.find { |bp| bp.name == 'Embed App Extensions' }
  unless embed_phase
    embed_phase = project.new(Xcodeproj::Project::Object::PBXCopyFilesBuildPhase)
    embed_phase.name = 'Embed App Extensions'
    embed_phase.dst_subfolder_spec = '13'
    runner_target.build_phases << embed_phase
  end

  build_file = embed_phase.add_file_reference(packet_target.product_reference, true)
  build_file.settings = { 'ATTRIBUTES' => ['RemoveHeadersOnCopy'] }

  runner_target.add_dependency(packet_target)
end

# Extension build settings
packet_target.build_configurations.each do |config|
  config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
  config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
  config.build_settings['CODE_SIGN_ENTITLEMENTS'] = 'PacketTunnel/PacketTunnel.entitlements'
  config.build_settings['GENERATE_INFOPLIST_FILE'] = 'NO'
  config.build_settings['INFOPLIST_FILE'] = 'PacketTunnel/Info.plist'
  config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = packet_tunnel_bundle_id
  config.build_settings['PRODUCT_NAME'] = '$(TARGET_NAME)'
  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
  config.build_settings['TARGETED_DEVICE_FAMILY'] = '1,2'
  config.build_settings['SWIFT_VERSION'] = '5.0'
  config.build_settings['SKIP_INSTALL'] = 'YES'
  config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = '$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks'
end

# Extension source/resource/frameworks
unless packet_target.source_build_phase.files_references.include?(provider_ref)
  packet_target.source_build_phase.add_file_reference(provider_ref)
end

# Info.plist should not be copied as a bundle resource for app extensions.
packet_target.resources_build_phase.files.each do |build_file|
  next unless build_file.file_ref == packet_info_ref

  packet_target.resources_build_phase.remove_build_file(build_file)
end

unless packet_target.frameworks_build_phase.files_references.include?(network_ext_ref)
  packet_target.frameworks_build_phase.add_file_reference(network_ext_ref)
end

project.save
puts 'Configured OrangePacketTunnel target successfully.'
